/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.1.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include <readonlylineedit.h>
#include "mycustomplot.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionSet_database;
    QAction *actionSaveAs;
    QAction *actionLoad;
    QAction *actionGenerate_report;
    QAction *actionGenerate_report_2;
    QAction *actionReport_Option;
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    MyCustomPlot *customPlot;
    QComboBox *comboBox_pumpmodel_qty;
    QLabel *label_1;
    QComboBox *comboBox_model_number;
    QLabel *label_2;
    QGroupBox *groupBox_1;
    QPushButton *pushButton_import_pump_curve;
    QComboBox *comboBox_choose_pump_curve;
    QLabel *label_3;
    QPushButton *pushButton_plot_pump_curve;
    QPushButton *pushButton_plot_assembly_curve;
    QGroupBox *groupBox_3;
    QPushButton *pushButton_import_piping_curve;
    QPushButton *pushButton_plot_piping_curve;
    QComboBox *comboBox_pump_qty;
    QLabel *label_11;
    QPushButton *pushButton_show_import_result;
    QPlainTextEdit *plainTextEdit_import_result;
    QWidget *tab_2;
    MyCustomPlot *customPlot_2;
    QPushButton *pushButton_plot_sensorless_curve;
    QLabel *label_4;
    QComboBox *comboBox_choose_sensorless_curve;
    QComboBox *comboBox_model_number_2;
    QLabel *label_5;
    QLineEdit *lineEdit_Hz;
    QLabel *label_6;
    QWidget *tab_3;
    MyCustomPlot *customPlot_3;
    QLabel *label_7;
    QComboBox *comboBox_model_number_3;
    QPushButton *pushButton_plot_vfd_curve;
    QLineEdit *lineEdit_flow;
    QLabel *label_8;
    QLineEdit *lineEdit_head;
    QLabel *label_9;
    QLineEdit *lineEdit_Hz_calculated;
    QLabel *label_10;
    QPushButton *pushButton_Hz_calculation;
    QWidget *tab_4;
    QLabel *label_12;
    QLabel *label_13;
    QLineEdit *lineEdit_target_head;
    QLineEdit *lineEdit_target_flow;
    QPushButton *pushButton_energy_saving_calculation;
    QPlainTextEdit *plainTextEdit_energy_saving_result;
    QWidget *tab_5;
    MyCustomPlot *customPlot_demo;
    QLabel *label_p1;
    QLabel *label_p2;
    QLabel *label_p3;
    QLabel *label_p4;
    QLabel *label_p5;
    QLabel *label_p6;
    ReadOnlyLineEdit *Edit_drive_type_p1;
    ReadOnlyLineEdit *Edit_drive_type_p2;
    ReadOnlyLineEdit *Edit_drive_type_p3;
    ReadOnlyLineEdit *Edit_drive_type_p4;
    ReadOnlyLineEdit *Edit_drive_type_p5;
    ReadOnlyLineEdit *Edit_drive_type_p6;
    ReadOnlyLineEdit *Edit_Hz_p1;
    ReadOnlyLineEdit *Edit_Hz_p2;
    ReadOnlyLineEdit *Edit_Hz_p3;
    ReadOnlyLineEdit *Edit_Hz_p4;
    ReadOnlyLineEdit *Edit_Hz_p5;
    ReadOnlyLineEdit *Edit_Hz_p6;
    ReadOnlyLineEdit *Edit_power_p1;
    ReadOnlyLineEdit *Edit_power_p2;
    ReadOnlyLineEdit *Edit_power_p3;
    ReadOnlyLineEdit *Edit_power_p4;
    ReadOnlyLineEdit *Edit_power_p5;
    ReadOnlyLineEdit *Edit_power_p6;
    ReadOnlyLineEdit *Edit_flow_p1;
    ReadOnlyLineEdit *Edit_flow_p2;
    ReadOnlyLineEdit *Edit_flow_p3;
    ReadOnlyLineEdit *Edit_flow_p4;
    ReadOnlyLineEdit *Edit_flow_p5;
    ReadOnlyLineEdit *Edit_flow_p6;
    QLabel *label_uint_Hz;
    QLabel *label_uint_kW;
    QLabel *label_uint_kW_2;
    QLineEdit *lineEdit_flow_start;
    QLabel *label_27;
    QLineEdit *lineEdit_flow_stop;
    QPushButton *pushButton_demo_start;
    ReadOnlyLineEdit *Edit_flow_total;
    ReadOnlyLineEdit *Edit_head;
    ReadOnlyLineEdit *Edit_efficiency;
    QLabel *label_img_p3;
    QLabel *label_img_p4;
    QLabel *label_img_p6;
    QLabel *label_img_p5;
    QLabel *label_img_p2;
    QLabel *label_img_p1;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_uint_kW_3;
    QLabel *label_uint_kW_4;
    QLabel *label_uint_Hz_2;
    QLabel *label_32;
    ReadOnlyLineEdit *Edit_power_total;
    QLabel *label_uint_kW_5;
    QLabel *label_uint_kW_6;
    QLabel *label_uint_kW_7;
    QPushButton *pushButton_demo_clear;
    QPushButton *pushButton_test;
    QMenuBar *menuBar;
    QMenu *menuSet_DB;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1004, 700);
        actionSet_database = new QAction(MainWindow);
        actionSet_database->setObjectName(QString::fromUtf8("actionSet_database"));
        actionSaveAs = new QAction(MainWindow);
        actionSaveAs->setObjectName(QString::fromUtf8("actionSaveAs"));
        actionLoad = new QAction(MainWindow);
        actionLoad->setObjectName(QString::fromUtf8("actionLoad"));
        actionGenerate_report = new QAction(MainWindow);
        actionGenerate_report->setObjectName(QString::fromUtf8("actionGenerate_report"));
        actionGenerate_report_2 = new QAction(MainWindow);
        actionGenerate_report_2->setObjectName(QString::fromUtf8("actionGenerate_report_2"));
        actionGenerate_report_2->setEnabled(true);
        actionReport_Option = new QAction(MainWindow);
        actionReport_Option->setObjectName(QString::fromUtf8("actionReport_Option"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 0, 991, 629));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(tabWidget->sizePolicy().hasHeightForWidth());
        tabWidget->setSizePolicy(sizePolicy);
        QFont font;
        tabWidget->setFont(font);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        customPlot = new MyCustomPlot(tab);
        customPlot->setObjectName(QString::fromUtf8("customPlot"));
        customPlot->setGeometry(QRect(190, 0, 791, 591));
        customPlot->setStyleSheet(QString::fromUtf8("font: 9pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        comboBox_pumpmodel_qty = new QComboBox(tab);
        comboBox_pumpmodel_qty->addItem(QString());
        comboBox_pumpmodel_qty->addItem(QString());
        comboBox_pumpmodel_qty->addItem(QString());
        comboBox_pumpmodel_qty->addItem(QString());
        comboBox_pumpmodel_qty->setObjectName(QString::fromUtf8("comboBox_pumpmodel_qty"));
        comboBox_pumpmodel_qty->setGeometry(QRect(20, 35, 151, 23));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(comboBox_pumpmodel_qty->sizePolicy().hasHeightForWidth());
        comboBox_pumpmodel_qty->setSizePolicy(sizePolicy1);
        label_1 = new QLabel(tab);
        label_1->setObjectName(QString::fromUtf8("label_1"));
        label_1->setGeometry(QRect(20, 14, 90, 16));
        sizePolicy.setHeightForWidth(label_1->sizePolicy().hasHeightForWidth());
        label_1->setSizePolicy(sizePolicy);
        label_1->setFont(font);
        comboBox_model_number = new QComboBox(tab);
        comboBox_model_number->addItem(QString());
        comboBox_model_number->setObjectName(QString::fromUtf8("comboBox_model_number"));
        comboBox_model_number->setGeometry(QRect(20, 85, 151, 23));
        sizePolicy1.setHeightForWidth(comboBox_model_number->sizePolicy().hasHeightForWidth());
        comboBox_model_number->setSizePolicy(sizePolicy1);
        label_2 = new QLabel(tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 64, 141, 16));
        sizePolicy.setHeightForWidth(label_2->sizePolicy().hasHeightForWidth());
        label_2->setSizePolicy(sizePolicy);
        label_2->setFont(font);
        groupBox_1 = new QGroupBox(tab);
        groupBox_1->setObjectName(QString::fromUtf8("groupBox_1"));
        groupBox_1->setGeometry(QRect(10, 170, 171, 166));
        pushButton_import_pump_curve = new QPushButton(groupBox_1);
        pushButton_import_pump_curve->setObjectName(QString::fromUtf8("pushButton_import_pump_curve"));
        pushButton_import_pump_curve->setGeometry(QRect(10, 20, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_import_pump_curve->sizePolicy().hasHeightForWidth());
        pushButton_import_pump_curve->setSizePolicy(sizePolicy);
        QFont font1;
        font1.setBold(false);
        pushButton_import_pump_curve->setFont(font1);
        comboBox_choose_pump_curve = new QComboBox(groupBox_1);
        comboBox_choose_pump_curve->addItem(QString());
        comboBox_choose_pump_curve->addItem(QString());
        comboBox_choose_pump_curve->addItem(QString());
        comboBox_choose_pump_curve->addItem(QString());
        comboBox_choose_pump_curve->addItem(QString());
        comboBox_choose_pump_curve->setObjectName(QString::fromUtf8("comboBox_choose_pump_curve"));
        comboBox_choose_pump_curve->setGeometry(QRect(10, 70, 151, 23));
        sizePolicy1.setHeightForWidth(comboBox_choose_pump_curve->sizePolicy().hasHeightForWidth());
        comboBox_choose_pump_curve->setSizePolicy(sizePolicy1);
        label_3 = new QLabel(groupBox_1);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 49, 112, 16));
        sizePolicy.setHeightForWidth(label_3->sizePolicy().hasHeightForWidth());
        label_3->setSizePolicy(sizePolicy);
        label_3->setFont(font);
        pushButton_plot_pump_curve = new QPushButton(groupBox_1);
        pushButton_plot_pump_curve->setObjectName(QString::fromUtf8("pushButton_plot_pump_curve"));
        pushButton_plot_pump_curve->setGeometry(QRect(10, 100, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_plot_pump_curve->sizePolicy().hasHeightForWidth());
        pushButton_plot_pump_curve->setSizePolicy(sizePolicy);
        pushButton_plot_pump_curve->setFont(font1);
        pushButton_plot_assembly_curve = new QPushButton(groupBox_1);
        pushButton_plot_assembly_curve->setObjectName(QString::fromUtf8("pushButton_plot_assembly_curve"));
        pushButton_plot_assembly_curve->setGeometry(QRect(10, 130, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_plot_assembly_curve->sizePolicy().hasHeightForWidth());
        pushButton_plot_assembly_curve->setSizePolicy(sizePolicy);
        pushButton_plot_assembly_curve->setFont(font1);
        groupBox_3 = new QGroupBox(tab);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 340, 171, 86));
        pushButton_import_piping_curve = new QPushButton(groupBox_3);
        pushButton_import_piping_curve->setObjectName(QString::fromUtf8("pushButton_import_piping_curve"));
        pushButton_import_piping_curve->setGeometry(QRect(10, 20, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_import_piping_curve->sizePolicy().hasHeightForWidth());
        pushButton_import_piping_curve->setSizePolicy(sizePolicy);
        pushButton_import_piping_curve->setFont(font1);
        pushButton_plot_piping_curve = new QPushButton(groupBox_3);
        pushButton_plot_piping_curve->setObjectName(QString::fromUtf8("pushButton_plot_piping_curve"));
        pushButton_plot_piping_curve->setGeometry(QRect(10, 50, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_plot_piping_curve->sizePolicy().hasHeightForWidth());
        pushButton_plot_piping_curve->setSizePolicy(sizePolicy);
        pushButton_plot_piping_curve->setFont(font1);
        comboBox_pump_qty = new QComboBox(tab);
        comboBox_pump_qty->addItem(QString());
        comboBox_pump_qty->addItem(QString());
        comboBox_pump_qty->addItem(QString());
        comboBox_pump_qty->addItem(QString());
        comboBox_pump_qty->addItem(QString());
        comboBox_pump_qty->addItem(QString());
        comboBox_pump_qty->addItem(QString());
        comboBox_pump_qty->addItem(QString());
        comboBox_pump_qty->addItem(QString());
        comboBox_pump_qty->setObjectName(QString::fromUtf8("comboBox_pump_qty"));
        comboBox_pump_qty->setGeometry(QRect(20, 135, 151, 23));
        sizePolicy1.setHeightForWidth(comboBox_pump_qty->sizePolicy().hasHeightForWidth());
        comboBox_pump_qty->setSizePolicy(sizePolicy1);
        label_11 = new QLabel(tab);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(20, 114, 106, 16));
        sizePolicy.setHeightForWidth(label_11->sizePolicy().hasHeightForWidth());
        label_11->setSizePolicy(sizePolicy);
        label_11->setFont(font);
        pushButton_show_import_result = new QPushButton(tab);
        pushButton_show_import_result->setObjectName(QString::fromUtf8("pushButton_show_import_result"));
        pushButton_show_import_result->setGeometry(QRect(20, 435, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_show_import_result->sizePolicy().hasHeightForWidth());
        pushButton_show_import_result->setSizePolicy(sizePolicy);
        pushButton_show_import_result->setFont(font1);
        plainTextEdit_import_result = new QPlainTextEdit(tab);
        plainTextEdit_import_result->setObjectName(QString::fromUtf8("plainTextEdit_import_result"));
        plainTextEdit_import_result->setEnabled(true);
        plainTextEdit_import_result->setGeometry(QRect(20, 465, 151, 126));
        plainTextEdit_import_result->setAutoFillBackground(false);
        plainTextEdit_import_result->setStyleSheet(QString::fromUtf8("background-color: rgb(225, 225, 225);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(173, 173, 173);"));
        plainTextEdit_import_result->setUndoRedoEnabled(false);
        plainTextEdit_import_result->setReadOnly(true);
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        customPlot_2 = new MyCustomPlot(tab_2);
        customPlot_2->setObjectName(QString::fromUtf8("customPlot_2"));
        customPlot_2->setGeometry(QRect(190, 0, 791, 591));
        pushButton_plot_sensorless_curve = new QPushButton(tab_2);
        pushButton_plot_sensorless_curve->setObjectName(QString::fromUtf8("pushButton_plot_sensorless_curve"));
        pushButton_plot_sensorless_curve->setGeometry(QRect(20, 170, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_plot_sensorless_curve->sizePolicy().hasHeightForWidth());
        pushButton_plot_sensorless_curve->setSizePolicy(sizePolicy);
        pushButton_plot_sensorless_curve->setFont(font1);
        label_4 = new QLabel(tab_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(20, 15, 141, 16));
        sizePolicy.setHeightForWidth(label_4->sizePolicy().hasHeightForWidth());
        label_4->setSizePolicy(sizePolicy);
        label_4->setFont(font);
        comboBox_choose_sensorless_curve = new QComboBox(tab_2);
        comboBox_choose_sensorless_curve->addItem(QString());
        comboBox_choose_sensorless_curve->addItem(QString());
        comboBox_choose_sensorless_curve->setObjectName(QString::fromUtf8("comboBox_choose_sensorless_curve"));
        comboBox_choose_sensorless_curve->setGeometry(QRect(20, 140, 151, 23));
        sizePolicy1.setHeightForWidth(comboBox_choose_sensorless_curve->sizePolicy().hasHeightForWidth());
        comboBox_choose_sensorless_curve->setSizePolicy(sizePolicy1);
        comboBox_model_number_2 = new QComboBox(tab_2);
        comboBox_model_number_2->addItem(QString());
        comboBox_model_number_2->setObjectName(QString::fromUtf8("comboBox_model_number_2"));
        comboBox_model_number_2->setGeometry(QRect(20, 36, 151, 23));
        sizePolicy1.setHeightForWidth(comboBox_model_number_2->sizePolicy().hasHeightForWidth());
        comboBox_model_number_2->setSizePolicy(sizePolicy1);
        label_5 = new QLabel(tab_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(20, 119, 112, 16));
        sizePolicy.setHeightForWidth(label_5->sizePolicy().hasHeightForWidth());
        label_5->setSizePolicy(sizePolicy);
        label_5->setFont(font);
        lineEdit_Hz = new QLineEdit(tab_2);
        lineEdit_Hz->setObjectName(QString::fromUtf8("lineEdit_Hz"));
        lineEdit_Hz->setGeometry(QRect(20, 90, 151, 23));
        lineEdit_Hz->setMaxLength(32767);
        lineEdit_Hz->setClearButtonEnabled(false);
        label_6 = new QLabel(tab_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(20, 70, 112, 16));
        sizePolicy.setHeightForWidth(label_6->sizePolicy().hasHeightForWidth());
        label_6->setSizePolicy(sizePolicy);
        label_6->setFont(font);
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        customPlot_3 = new MyCustomPlot(tab_3);
        customPlot_3->setObjectName(QString::fromUtf8("customPlot_3"));
        customPlot_3->setGeometry(QRect(190, 0, 791, 591));
        label_7 = new QLabel(tab_3);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(20, 15, 141, 16));
        sizePolicy.setHeightForWidth(label_7->sizePolicy().hasHeightForWidth());
        label_7->setSizePolicy(sizePolicy);
        label_7->setFont(font);
        comboBox_model_number_3 = new QComboBox(tab_3);
        comboBox_model_number_3->addItem(QString());
        comboBox_model_number_3->setObjectName(QString::fromUtf8("comboBox_model_number_3"));
        comboBox_model_number_3->setGeometry(QRect(20, 36, 151, 23));
        sizePolicy1.setHeightForWidth(comboBox_model_number_3->sizePolicy().hasHeightForWidth());
        comboBox_model_number_3->setSizePolicy(sizePolicy1);
        pushButton_plot_vfd_curve = new QPushButton(tab_3);
        pushButton_plot_vfd_curve->setObjectName(QString::fromUtf8("pushButton_plot_vfd_curve"));
        pushButton_plot_vfd_curve->setGeometry(QRect(20, 255, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_plot_vfd_curve->sizePolicy().hasHeightForWidth());
        pushButton_plot_vfd_curve->setSizePolicy(sizePolicy);
        pushButton_plot_vfd_curve->setFont(font1);
        lineEdit_flow = new QLineEdit(tab_3);
        lineEdit_flow->setObjectName(QString::fromUtf8("lineEdit_flow"));
        lineEdit_flow->setGeometry(QRect(20, 85, 151, 23));
        lineEdit_flow->setMaxLength(32767);
        lineEdit_flow->setClearButtonEnabled(false);
        label_8 = new QLabel(tab_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(20, 65, 112, 16));
        sizePolicy.setHeightForWidth(label_8->sizePolicy().hasHeightForWidth());
        label_8->setSizePolicy(sizePolicy);
        label_8->setFont(font);
        lineEdit_head = new QLineEdit(tab_3);
        lineEdit_head->setObjectName(QString::fromUtf8("lineEdit_head"));
        lineEdit_head->setGeometry(QRect(20, 135, 151, 23));
        lineEdit_head->setMaxLength(32767);
        lineEdit_head->setReadOnly(false);
        lineEdit_head->setClearButtonEnabled(false);
        label_9 = new QLabel(tab_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(20, 115, 112, 16));
        sizePolicy.setHeightForWidth(label_9->sizePolicy().hasHeightForWidth());
        label_9->setSizePolicy(sizePolicy);
        label_9->setFont(font);
        lineEdit_Hz_calculated = new QLineEdit(tab_3);
        lineEdit_Hz_calculated->setObjectName(QString::fromUtf8("lineEdit_Hz_calculated"));
        lineEdit_Hz_calculated->setEnabled(true);
        lineEdit_Hz_calculated->setGeometry(QRect(20, 220, 151, 23));
        lineEdit_Hz_calculated->setStyleSheet(QString::fromUtf8("background-color: rgb(225, 225, 225);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(173, 173, 173);"));
        lineEdit_Hz_calculated->setMaxLength(32767);
        lineEdit_Hz_calculated->setReadOnly(true);
        lineEdit_Hz_calculated->setClearButtonEnabled(false);
        label_10 = new QLabel(tab_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(20, 200, 112, 16));
        sizePolicy.setHeightForWidth(label_10->sizePolicy().hasHeightForWidth());
        label_10->setSizePolicy(sizePolicy);
        label_10->setFont(font);
        pushButton_Hz_calculation = new QPushButton(tab_3);
        pushButton_Hz_calculation->setObjectName(QString::fromUtf8("pushButton_Hz_calculation"));
        pushButton_Hz_calculation->setGeometry(QRect(20, 170, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_Hz_calculation->sizePolicy().hasHeightForWidth());
        pushButton_Hz_calculation->setSizePolicy(sizePolicy);
        pushButton_Hz_calculation->setFont(font1);
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        label_12 = new QLabel(tab_4);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(20, 15, 112, 16));
        sizePolicy.setHeightForWidth(label_12->sizePolicy().hasHeightForWidth());
        label_12->setSizePolicy(sizePolicy);
        label_12->setFont(font);
        label_13 = new QLabel(tab_4);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(20, 65, 112, 16));
        sizePolicy.setHeightForWidth(label_13->sizePolicy().hasHeightForWidth());
        label_13->setSizePolicy(sizePolicy);
        label_13->setFont(font);
        lineEdit_target_head = new QLineEdit(tab_4);
        lineEdit_target_head->setObjectName(QString::fromUtf8("lineEdit_target_head"));
        lineEdit_target_head->setEnabled(true);
        lineEdit_target_head->setGeometry(QRect(20, 85, 151, 23));
        lineEdit_target_head->setAutoFillBackground(false);
        lineEdit_target_head->setStyleSheet(QString::fromUtf8(""));
        lineEdit_target_head->setMaxLength(32767);
        lineEdit_target_head->setReadOnly(false);
        lineEdit_target_head->setClearButtonEnabled(false);
        lineEdit_target_flow = new QLineEdit(tab_4);
        lineEdit_target_flow->setObjectName(QString::fromUtf8("lineEdit_target_flow"));
        lineEdit_target_flow->setGeometry(QRect(20, 35, 151, 23));
        lineEdit_target_flow->setMaxLength(32767);
        lineEdit_target_flow->setClearButtonEnabled(false);
        pushButton_energy_saving_calculation = new QPushButton(tab_4);
        pushButton_energy_saving_calculation->setObjectName(QString::fromUtf8("pushButton_energy_saving_calculation"));
        pushButton_energy_saving_calculation->setGeometry(QRect(20, 115, 151, 25));
        sizePolicy.setHeightForWidth(pushButton_energy_saving_calculation->sizePolicy().hasHeightForWidth());
        pushButton_energy_saving_calculation->setSizePolicy(sizePolicy);
        pushButton_energy_saving_calculation->setFont(font1);
        plainTextEdit_energy_saving_result = new QPlainTextEdit(tab_4);
        plainTextEdit_energy_saving_result->setObjectName(QString::fromUtf8("plainTextEdit_energy_saving_result"));
        plainTextEdit_energy_saving_result->setEnabled(true);
        plainTextEdit_energy_saving_result->setGeometry(QRect(20, 150, 151, 441));
        QFont font2;
        font2.setPointSize(8);
        plainTextEdit_energy_saving_result->setFont(font2);
        plainTextEdit_energy_saving_result->setStyleSheet(QString::fromUtf8("background-color: rgb(225, 225, 225);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(173, 173, 173);"));
        plainTextEdit_energy_saving_result->setReadOnly(true);
        plainTextEdit_energy_saving_result->setBackgroundVisible(false);
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        customPlot_demo = new MyCustomPlot(tab_5);
        customPlot_demo->setObjectName(QString::fromUtf8("customPlot_demo"));
        customPlot_demo->setGeometry(QRect(50, 40, 881, 341));
        customPlot_demo->setStyleSheet(QString::fromUtf8("font: 9pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        label_p1 = new QLabel(tab_5);
        label_p1->setObjectName(QString::fromUtf8("label_p1"));
        label_p1->setGeometry(QRect(537, 462, 51, 17));
        label_p1->setAlignment(Qt::AlignCenter);
        label_p2 = new QLabel(tab_5);
        label_p2->setObjectName(QString::fromUtf8("label_p2"));
        label_p2->setGeometry(QRect(594, 462, 51, 17));
        label_p2->setAlignment(Qt::AlignCenter);
        label_p3 = new QLabel(tab_5);
        label_p3->setObjectName(QString::fromUtf8("label_p3"));
        label_p3->setGeometry(QRect(651, 462, 51, 17));
        label_p3->setAlignment(Qt::AlignCenter);
        label_p4 = new QLabel(tab_5);
        label_p4->setObjectName(QString::fromUtf8("label_p4"));
        label_p4->setGeometry(QRect(708, 462, 51, 17));
        label_p4->setAlignment(Qt::AlignCenter);
        label_p5 = new QLabel(tab_5);
        label_p5->setObjectName(QString::fromUtf8("label_p5"));
        label_p5->setGeometry(QRect(765, 462, 51, 17));
        label_p5->setAlignment(Qt::AlignCenter);
        label_p6 = new QLabel(tab_5);
        label_p6->setObjectName(QString::fromUtf8("label_p6"));
        label_p6->setGeometry(QRect(822, 462, 51, 17));
        label_p6->setAlignment(Qt::AlignCenter);
        Edit_drive_type_p1 = new ReadOnlyLineEdit(tab_5);
        Edit_drive_type_p1->setObjectName(QString::fromUtf8("Edit_drive_type_p1"));
        Edit_drive_type_p1->setGeometry(QRect(537, 480, 51, 20));
        Edit_drive_type_p1->setCursor(QCursor(Qt::ArrowCursor));
        Edit_drive_type_p1->setMouseTracking(false);
        Edit_drive_type_p1->setFocusPolicy(Qt::NoFocus);
        Edit_drive_type_p1->setAcceptDrops(false);
        Edit_drive_type_p1->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_drive_type_p1->setAlignment(Qt::AlignCenter);
        Edit_drive_type_p2 = new ReadOnlyLineEdit(tab_5);
        Edit_drive_type_p2->setObjectName(QString::fromUtf8("Edit_drive_type_p2"));
        Edit_drive_type_p2->setGeometry(QRect(594, 480, 51, 20));
        Edit_drive_type_p2->setCursor(QCursor(Qt::ArrowCursor));
        Edit_drive_type_p2->setMouseTracking(false);
        Edit_drive_type_p2->setFocusPolicy(Qt::NoFocus);
        Edit_drive_type_p2->setAcceptDrops(false);
        Edit_drive_type_p2->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_drive_type_p2->setAlignment(Qt::AlignCenter);
        Edit_drive_type_p3 = new ReadOnlyLineEdit(tab_5);
        Edit_drive_type_p3->setObjectName(QString::fromUtf8("Edit_drive_type_p3"));
        Edit_drive_type_p3->setGeometry(QRect(651, 480, 51, 20));
        Edit_drive_type_p3->setCursor(QCursor(Qt::ArrowCursor));
        Edit_drive_type_p3->setMouseTracking(false);
        Edit_drive_type_p3->setFocusPolicy(Qt::NoFocus);
        Edit_drive_type_p3->setAcceptDrops(false);
        Edit_drive_type_p3->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_drive_type_p3->setAlignment(Qt::AlignCenter);
        Edit_drive_type_p4 = new ReadOnlyLineEdit(tab_5);
        Edit_drive_type_p4->setObjectName(QString::fromUtf8("Edit_drive_type_p4"));
        Edit_drive_type_p4->setGeometry(QRect(708, 480, 51, 20));
        Edit_drive_type_p4->setCursor(QCursor(Qt::ArrowCursor));
        Edit_drive_type_p4->setMouseTracking(false);
        Edit_drive_type_p4->setFocusPolicy(Qt::NoFocus);
        Edit_drive_type_p4->setAcceptDrops(false);
        Edit_drive_type_p4->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_drive_type_p4->setAlignment(Qt::AlignCenter);
        Edit_drive_type_p5 = new ReadOnlyLineEdit(tab_5);
        Edit_drive_type_p5->setObjectName(QString::fromUtf8("Edit_drive_type_p5"));
        Edit_drive_type_p5->setGeometry(QRect(765, 480, 51, 20));
        Edit_drive_type_p5->setCursor(QCursor(Qt::ArrowCursor));
        Edit_drive_type_p5->setMouseTracking(false);
        Edit_drive_type_p5->setFocusPolicy(Qt::NoFocus);
        Edit_drive_type_p5->setAcceptDrops(false);
        Edit_drive_type_p5->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_drive_type_p5->setAlignment(Qt::AlignCenter);
        Edit_drive_type_p6 = new ReadOnlyLineEdit(tab_5);
        Edit_drive_type_p6->setObjectName(QString::fromUtf8("Edit_drive_type_p6"));
        Edit_drive_type_p6->setGeometry(QRect(822, 480, 51, 20));
        Edit_drive_type_p6->setCursor(QCursor(Qt::ArrowCursor));
        Edit_drive_type_p6->setMouseTracking(false);
        Edit_drive_type_p6->setFocusPolicy(Qt::NoFocus);
        Edit_drive_type_p6->setAcceptDrops(false);
        Edit_drive_type_p6->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_drive_type_p6->setAlignment(Qt::AlignCenter);
        Edit_Hz_p1 = new ReadOnlyLineEdit(tab_5);
        Edit_Hz_p1->setObjectName(QString::fromUtf8("Edit_Hz_p1"));
        Edit_Hz_p1->setGeometry(QRect(537, 501, 51, 20));
        Edit_Hz_p1->setCursor(QCursor(Qt::ArrowCursor));
        Edit_Hz_p1->setMouseTracking(false);
        Edit_Hz_p1->setFocusPolicy(Qt::NoFocus);
        Edit_Hz_p1->setAcceptDrops(false);
        Edit_Hz_p1->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_Hz_p1->setAlignment(Qt::AlignCenter);
        Edit_Hz_p2 = new ReadOnlyLineEdit(tab_5);
        Edit_Hz_p2->setObjectName(QString::fromUtf8("Edit_Hz_p2"));
        Edit_Hz_p2->setGeometry(QRect(594, 501, 51, 20));
        Edit_Hz_p2->setCursor(QCursor(Qt::ArrowCursor));
        Edit_Hz_p2->setMouseTracking(false);
        Edit_Hz_p2->setFocusPolicy(Qt::NoFocus);
        Edit_Hz_p2->setAcceptDrops(false);
        Edit_Hz_p2->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_Hz_p2->setAlignment(Qt::AlignCenter);
        Edit_Hz_p3 = new ReadOnlyLineEdit(tab_5);
        Edit_Hz_p3->setObjectName(QString::fromUtf8("Edit_Hz_p3"));
        Edit_Hz_p3->setGeometry(QRect(651, 501, 51, 20));
        Edit_Hz_p3->setCursor(QCursor(Qt::ArrowCursor));
        Edit_Hz_p3->setMouseTracking(false);
        Edit_Hz_p3->setFocusPolicy(Qt::NoFocus);
        Edit_Hz_p3->setAcceptDrops(false);
        Edit_Hz_p3->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_Hz_p3->setAlignment(Qt::AlignCenter);
        Edit_Hz_p4 = new ReadOnlyLineEdit(tab_5);
        Edit_Hz_p4->setObjectName(QString::fromUtf8("Edit_Hz_p4"));
        Edit_Hz_p4->setGeometry(QRect(708, 501, 51, 20));
        Edit_Hz_p4->setCursor(QCursor(Qt::ArrowCursor));
        Edit_Hz_p4->setMouseTracking(false);
        Edit_Hz_p4->setFocusPolicy(Qt::NoFocus);
        Edit_Hz_p4->setAcceptDrops(false);
        Edit_Hz_p4->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_Hz_p4->setAlignment(Qt::AlignCenter);
        Edit_Hz_p5 = new ReadOnlyLineEdit(tab_5);
        Edit_Hz_p5->setObjectName(QString::fromUtf8("Edit_Hz_p5"));
        Edit_Hz_p5->setGeometry(QRect(765, 501, 51, 20));
        Edit_Hz_p5->setCursor(QCursor(Qt::ArrowCursor));
        Edit_Hz_p5->setMouseTracking(false);
        Edit_Hz_p5->setFocusPolicy(Qt::NoFocus);
        Edit_Hz_p5->setAcceptDrops(false);
        Edit_Hz_p5->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_Hz_p5->setAlignment(Qt::AlignCenter);
        Edit_Hz_p6 = new ReadOnlyLineEdit(tab_5);
        Edit_Hz_p6->setObjectName(QString::fromUtf8("Edit_Hz_p6"));
        Edit_Hz_p6->setGeometry(QRect(822, 501, 51, 20));
        Edit_Hz_p6->setCursor(QCursor(Qt::ArrowCursor));
        Edit_Hz_p6->setMouseTracking(false);
        Edit_Hz_p6->setFocusPolicy(Qt::NoFocus);
        Edit_Hz_p6->setAcceptDrops(false);
        Edit_Hz_p6->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_Hz_p6->setAlignment(Qt::AlignCenter);
        Edit_power_p1 = new ReadOnlyLineEdit(tab_5);
        Edit_power_p1->setObjectName(QString::fromUtf8("Edit_power_p1"));
        Edit_power_p1->setGeometry(QRect(537, 522, 51, 20));
        Edit_power_p1->setCursor(QCursor(Qt::ArrowCursor));
        Edit_power_p1->setMouseTracking(false);
        Edit_power_p1->setFocusPolicy(Qt::NoFocus);
        Edit_power_p1->setAcceptDrops(false);
        Edit_power_p1->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_power_p1->setAlignment(Qt::AlignCenter);
        Edit_power_p2 = new ReadOnlyLineEdit(tab_5);
        Edit_power_p2->setObjectName(QString::fromUtf8("Edit_power_p2"));
        Edit_power_p2->setGeometry(QRect(594, 522, 51, 20));
        Edit_power_p2->setCursor(QCursor(Qt::ArrowCursor));
        Edit_power_p2->setMouseTracking(false);
        Edit_power_p2->setFocusPolicy(Qt::NoFocus);
        Edit_power_p2->setAcceptDrops(false);
        Edit_power_p2->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_power_p2->setAlignment(Qt::AlignCenter);
        Edit_power_p3 = new ReadOnlyLineEdit(tab_5);
        Edit_power_p3->setObjectName(QString::fromUtf8("Edit_power_p3"));
        Edit_power_p3->setGeometry(QRect(651, 522, 51, 20));
        Edit_power_p3->setCursor(QCursor(Qt::ArrowCursor));
        Edit_power_p3->setMouseTracking(false);
        Edit_power_p3->setFocusPolicy(Qt::NoFocus);
        Edit_power_p3->setAcceptDrops(false);
        Edit_power_p3->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_power_p3->setAlignment(Qt::AlignCenter);
        Edit_power_p4 = new ReadOnlyLineEdit(tab_5);
        Edit_power_p4->setObjectName(QString::fromUtf8("Edit_power_p4"));
        Edit_power_p4->setGeometry(QRect(708, 522, 51, 20));
        Edit_power_p4->setCursor(QCursor(Qt::ArrowCursor));
        Edit_power_p4->setMouseTracking(false);
        Edit_power_p4->setFocusPolicy(Qt::NoFocus);
        Edit_power_p4->setAcceptDrops(false);
        Edit_power_p4->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_power_p4->setAlignment(Qt::AlignCenter);
        Edit_power_p5 = new ReadOnlyLineEdit(tab_5);
        Edit_power_p5->setObjectName(QString::fromUtf8("Edit_power_p5"));
        Edit_power_p5->setGeometry(QRect(765, 522, 51, 20));
        Edit_power_p5->setCursor(QCursor(Qt::ArrowCursor));
        Edit_power_p5->setMouseTracking(false);
        Edit_power_p5->setFocusPolicy(Qt::NoFocus);
        Edit_power_p5->setAcceptDrops(false);
        Edit_power_p5->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_power_p5->setAlignment(Qt::AlignCenter);
        Edit_power_p6 = new ReadOnlyLineEdit(tab_5);
        Edit_power_p6->setObjectName(QString::fromUtf8("Edit_power_p6"));
        Edit_power_p6->setGeometry(QRect(822, 522, 51, 20));
        Edit_power_p6->setCursor(QCursor(Qt::ArrowCursor));
        Edit_power_p6->setMouseTracking(false);
        Edit_power_p6->setFocusPolicy(Qt::NoFocus);
        Edit_power_p6->setAcceptDrops(false);
        Edit_power_p6->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_power_p6->setAlignment(Qt::AlignCenter);
        Edit_flow_p1 = new ReadOnlyLineEdit(tab_5);
        Edit_flow_p1->setObjectName(QString::fromUtf8("Edit_flow_p1"));
        Edit_flow_p1->setGeometry(QRect(537, 543, 51, 20));
        Edit_flow_p1->setCursor(QCursor(Qt::ArrowCursor));
        Edit_flow_p1->setMouseTracking(false);
        Edit_flow_p1->setFocusPolicy(Qt::NoFocus);
        Edit_flow_p1->setAcceptDrops(false);
        Edit_flow_p1->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_flow_p1->setAlignment(Qt::AlignCenter);
        Edit_flow_p2 = new ReadOnlyLineEdit(tab_5);
        Edit_flow_p2->setObjectName(QString::fromUtf8("Edit_flow_p2"));
        Edit_flow_p2->setGeometry(QRect(594, 543, 51, 20));
        Edit_flow_p2->setCursor(QCursor(Qt::ArrowCursor));
        Edit_flow_p2->setMouseTracking(false);
        Edit_flow_p2->setFocusPolicy(Qt::NoFocus);
        Edit_flow_p2->setAcceptDrops(false);
        Edit_flow_p2->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_flow_p2->setAlignment(Qt::AlignCenter);
        Edit_flow_p3 = new ReadOnlyLineEdit(tab_5);
        Edit_flow_p3->setObjectName(QString::fromUtf8("Edit_flow_p3"));
        Edit_flow_p3->setGeometry(QRect(651, 543, 51, 20));
        Edit_flow_p3->setCursor(QCursor(Qt::ArrowCursor));
        Edit_flow_p3->setMouseTracking(false);
        Edit_flow_p3->setFocusPolicy(Qt::NoFocus);
        Edit_flow_p3->setAcceptDrops(false);
        Edit_flow_p3->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_flow_p3->setAlignment(Qt::AlignCenter);
        Edit_flow_p4 = new ReadOnlyLineEdit(tab_5);
        Edit_flow_p4->setObjectName(QString::fromUtf8("Edit_flow_p4"));
        Edit_flow_p4->setGeometry(QRect(708, 543, 51, 20));
        Edit_flow_p4->setCursor(QCursor(Qt::ArrowCursor));
        Edit_flow_p4->setMouseTracking(false);
        Edit_flow_p4->setFocusPolicy(Qt::NoFocus);
        Edit_flow_p4->setAcceptDrops(false);
        Edit_flow_p4->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_flow_p4->setAlignment(Qt::AlignCenter);
        Edit_flow_p5 = new ReadOnlyLineEdit(tab_5);
        Edit_flow_p5->setObjectName(QString::fromUtf8("Edit_flow_p5"));
        Edit_flow_p5->setGeometry(QRect(765, 543, 51, 20));
        Edit_flow_p5->setCursor(QCursor(Qt::ArrowCursor));
        Edit_flow_p5->setMouseTracking(false);
        Edit_flow_p5->setFocusPolicy(Qt::NoFocus);
        Edit_flow_p5->setAcceptDrops(false);
        Edit_flow_p5->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_flow_p5->setAlignment(Qt::AlignCenter);
        Edit_flow_p6 = new ReadOnlyLineEdit(tab_5);
        Edit_flow_p6->setObjectName(QString::fromUtf8("Edit_flow_p6"));
        Edit_flow_p6->setGeometry(QRect(822, 543, 51, 20));
        Edit_flow_p6->setCursor(QCursor(Qt::ArrowCursor));
        Edit_flow_p6->setMouseTracking(false);
        Edit_flow_p6->setFocusPolicy(Qt::NoFocus);
        Edit_flow_p6->setAcceptDrops(false);
        Edit_flow_p6->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_flow_p6->setAlignment(Qt::AlignCenter);
        label_uint_Hz = new QLabel(tab_5);
        label_uint_Hz->setObjectName(QString::fromUtf8("label_uint_Hz"));
        label_uint_Hz->setGeometry(QRect(880, 501, 31, 17));
        label_uint_Hz->setFont(font2);
        label_uint_Hz->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_uint_kW = new QLabel(tab_5);
        label_uint_kW->setObjectName(QString::fromUtf8("label_uint_kW"));
        label_uint_kW->setGeometry(QRect(880, 522, 31, 17));
        label_uint_kW->setFont(font2);
        label_uint_kW->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_uint_kW_2 = new QLabel(tab_5);
        label_uint_kW_2->setObjectName(QString::fromUtf8("label_uint_kW_2"));
        label_uint_kW_2->setGeometry(QRect(880, 543, 31, 17));
        label_uint_kW_2->setFont(font2);
        label_uint_kW_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_flow_start = new QLineEdit(tab_5);
        lineEdit_flow_start->setObjectName(QString::fromUtf8("lineEdit_flow_start"));
        lineEdit_flow_start->setGeometry(QRect(282, 480, 71, 20));
        lineEdit_flow_start->setFont(font2);
        lineEdit_flow_start->setMaxLength(32767);
        lineEdit_flow_start->setAlignment(Qt::AlignCenter);
        lineEdit_flow_start->setClearButtonEnabled(false);
        label_27 = new QLabel(tab_5);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(204, 480, 71, 16));
        sizePolicy.setHeightForWidth(label_27->sizePolicy().hasHeightForWidth());
        label_27->setSizePolicy(sizePolicy);
        label_27->setFont(font2);
        label_27->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_flow_stop = new QLineEdit(tab_5);
        lineEdit_flow_stop->setObjectName(QString::fromUtf8("lineEdit_flow_stop"));
        lineEdit_flow_stop->setGeometry(QRect(282, 501, 71, 20));
        lineEdit_flow_stop->setFont(font2);
        lineEdit_flow_stop->setMaxLength(32767);
        lineEdit_flow_stop->setAlignment(Qt::AlignCenter);
        lineEdit_flow_stop->setClearButtonEnabled(false);
        pushButton_demo_start = new QPushButton(tab_5);
        pushButton_demo_start->setObjectName(QString::fromUtf8("pushButton_demo_start"));
        pushButton_demo_start->setGeometry(QRect(420, 480, 71, 21));
        sizePolicy.setHeightForWidth(pushButton_demo_start->sizePolicy().hasHeightForWidth());
        pushButton_demo_start->setSizePolicy(sizePolicy);
        QFont font3;
        font3.setPointSize(8);
        font3.setBold(false);
        pushButton_demo_start->setFont(font3);
        Edit_flow_total = new ReadOnlyLineEdit(tab_5);
        Edit_flow_total->setObjectName(QString::fromUtf8("Edit_flow_total"));
        Edit_flow_total->setGeometry(QRect(92, 480, 71, 20));
        Edit_flow_total->setCursor(QCursor(Qt::ArrowCursor));
        Edit_flow_total->setMouseTracking(false);
        Edit_flow_total->setFocusPolicy(Qt::NoFocus);
        Edit_flow_total->setAcceptDrops(false);
        Edit_flow_total->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_flow_total->setAlignment(Qt::AlignCenter);
        Edit_head = new ReadOnlyLineEdit(tab_5);
        Edit_head->setObjectName(QString::fromUtf8("Edit_head"));
        Edit_head->setGeometry(QRect(92, 501, 71, 20));
        Edit_head->setCursor(QCursor(Qt::ArrowCursor));
        Edit_head->setMouseTracking(false);
        Edit_head->setFocusPolicy(Qt::NoFocus);
        Edit_head->setAcceptDrops(false);
        Edit_head->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_head->setAlignment(Qt::AlignCenter);
        Edit_efficiency = new ReadOnlyLineEdit(tab_5);
        Edit_efficiency->setObjectName(QString::fromUtf8("Edit_efficiency"));
        Edit_efficiency->setGeometry(QRect(92, 543, 71, 20));
        Edit_efficiency->setCursor(QCursor(Qt::ArrowCursor));
        Edit_efficiency->setMouseTracking(false);
        Edit_efficiency->setFocusPolicy(Qt::NoFocus);
        Edit_efficiency->setAcceptDrops(false);
        Edit_efficiency->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_efficiency->setAlignment(Qt::AlignCenter);
        label_img_p3 = new QLabel(tab_5);
        label_img_p3->setObjectName(QString::fromUtf8("label_img_p3"));
        label_img_p3->setGeometry(QRect(651, 410, 51, 47));
        label_img_p3->setPixmap(QPixmap(QString::fromUtf8("../../../../13525/Desktop/gray pump.png")));
        label_img_p4 = new QLabel(tab_5);
        label_img_p4->setObjectName(QString::fromUtf8("label_img_p4"));
        label_img_p4->setGeometry(QRect(708, 410, 51, 47));
        label_img_p4->setPixmap(QPixmap(QString::fromUtf8("../../../../13525/Desktop/gray pump.png")));
        label_img_p6 = new QLabel(tab_5);
        label_img_p6->setObjectName(QString::fromUtf8("label_img_p6"));
        label_img_p6->setGeometry(QRect(822, 410, 51, 47));
        label_img_p6->setPixmap(QPixmap(QString::fromUtf8("../../../../13525/Desktop/gray pump.png")));
        label_img_p5 = new QLabel(tab_5);
        label_img_p5->setObjectName(QString::fromUtf8("label_img_p5"));
        label_img_p5->setGeometry(QRect(765, 410, 51, 47));
        label_img_p5->setPixmap(QPixmap(QString::fromUtf8("../../../../13525/Desktop/gray pump.png")));
        label_img_p2 = new QLabel(tab_5);
        label_img_p2->setObjectName(QString::fromUtf8("label_img_p2"));
        label_img_p2->setGeometry(QRect(594, 410, 51, 47));
        label_img_p2->setPixmap(QPixmap(QString::fromUtf8("../../../../13525/Desktop/gray pump.png")));
        label_img_p1 = new QLabel(tab_5);
        label_img_p1->setObjectName(QString::fromUtf8("label_img_p1"));
        label_img_p1->setGeometry(QRect(537, 410, 51, 47));
        label_img_p1->setPixmap(QPixmap(QString::fromUtf8("../../../../13525/Desktop/gray pump.png")));
        label_28 = new QLabel(tab_5);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(204, 501, 71, 20));
        sizePolicy.setHeightForWidth(label_28->sizePolicy().hasHeightForWidth());
        label_28->setSizePolicy(sizePolicy);
        label_28->setFont(font2);
        label_28->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_29 = new QLabel(tab_5);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(14, 480, 71, 20));
        sizePolicy.setHeightForWidth(label_29->sizePolicy().hasHeightForWidth());
        label_29->setSizePolicy(sizePolicy);
        label_29->setFont(font2);
        label_29->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_30 = new QLabel(tab_5);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(14, 501, 71, 20));
        sizePolicy.setHeightForWidth(label_30->sizePolicy().hasHeightForWidth());
        label_30->setSizePolicy(sizePolicy);
        label_30->setFont(font2);
        label_30->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_31 = new QLabel(tab_5);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(14, 543, 71, 20));
        sizePolicy.setHeightForWidth(label_31->sizePolicy().hasHeightForWidth());
        label_31->setSizePolicy(sizePolicy);
        label_31->setFont(font2);
        label_31->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_uint_kW_3 = new QLabel(tab_5);
        label_uint_kW_3->setObjectName(QString::fromUtf8("label_uint_kW_3"));
        label_uint_kW_3->setGeometry(QRect(170, 522, 31, 17));
        label_uint_kW_3->setFont(font2);
        label_uint_kW_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_uint_kW_4 = new QLabel(tab_5);
        label_uint_kW_4->setObjectName(QString::fromUtf8("label_uint_kW_4"));
        label_uint_kW_4->setGeometry(QRect(170, 480, 31, 17));
        label_uint_kW_4->setFont(font2);
        label_uint_kW_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_uint_Hz_2 = new QLabel(tab_5);
        label_uint_Hz_2->setObjectName(QString::fromUtf8("label_uint_Hz_2"));
        label_uint_Hz_2->setGeometry(QRect(170, 543, 31, 17));
        label_uint_Hz_2->setFont(font2);
        label_uint_Hz_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_32 = new QLabel(tab_5);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(14, 522, 71, 20));
        sizePolicy.setHeightForWidth(label_32->sizePolicy().hasHeightForWidth());
        label_32->setSizePolicy(sizePolicy);
        label_32->setFont(font2);
        label_32->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        Edit_power_total = new ReadOnlyLineEdit(tab_5);
        Edit_power_total->setObjectName(QString::fromUtf8("Edit_power_total"));
        Edit_power_total->setGeometry(QRect(92, 522, 71, 20));
        Edit_power_total->setCursor(QCursor(Qt::ArrowCursor));
        Edit_power_total->setMouseTracking(false);
        Edit_power_total->setFocusPolicy(Qt::NoFocus);
        Edit_power_total->setAcceptDrops(false);
        Edit_power_total->setStyleSheet(QString::fromUtf8("font: 8pt \"Arial\";\n"
"background-color: rgb(240, 240, 240);"));
        Edit_power_total->setAlignment(Qt::AlignCenter);
        label_uint_kW_5 = new QLabel(tab_5);
        label_uint_kW_5->setObjectName(QString::fromUtf8("label_uint_kW_5"));
        label_uint_kW_5->setGeometry(QRect(170, 501, 31, 17));
        label_uint_kW_5->setFont(font2);
        label_uint_kW_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_uint_kW_6 = new QLabel(tab_5);
        label_uint_kW_6->setObjectName(QString::fromUtf8("label_uint_kW_6"));
        label_uint_kW_6->setGeometry(QRect(360, 501, 31, 17));
        label_uint_kW_6->setFont(font2);
        label_uint_kW_6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_uint_kW_7 = new QLabel(tab_5);
        label_uint_kW_7->setObjectName(QString::fromUtf8("label_uint_kW_7"));
        label_uint_kW_7->setGeometry(QRect(360, 480, 31, 17));
        label_uint_kW_7->setFont(font2);
        label_uint_kW_7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButton_demo_clear = new QPushButton(tab_5);
        pushButton_demo_clear->setObjectName(QString::fromUtf8("pushButton_demo_clear"));
        pushButton_demo_clear->setGeometry(QRect(420, 501, 71, 21));
        sizePolicy.setHeightForWidth(pushButton_demo_clear->sizePolicy().hasHeightForWidth());
        pushButton_demo_clear->setSizePolicy(sizePolicy);
        pushButton_demo_clear->setFont(font3);
        pushButton_test = new QPushButton(tab_5);
        pushButton_test->setObjectName(QString::fromUtf8("pushButton_test"));
        pushButton_test->setGeometry(QRect(430, 560, 71, 21));
        sizePolicy.setHeightForWidth(pushButton_test->sizePolicy().hasHeightForWidth());
        pushButton_test->setSizePolicy(sizePolicy);
        pushButton_test->setFont(font3);
        tabWidget->addTab(tab_5, QString());
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1004, 22));
        menuSet_DB = new QMenu(menuBar);
        menuSet_DB->setObjectName(QString::fromUtf8("menuSet_DB"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuSet_DB->menuAction());

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "Pumping System Curver", nullptr));
        actionSet_database->setText(QCoreApplication::translate("MainWindow", "Set database", nullptr));
        actionSaveAs->setText(QCoreApplication::translate("MainWindow", "Save config as...", nullptr));
        actionLoad->setText(QCoreApplication::translate("MainWindow", "Load config...", nullptr));
        actionGenerate_report->setText(QCoreApplication::translate("MainWindow", "Generate report", nullptr));
        actionGenerate_report_2->setText(QCoreApplication::translate("MainWindow", "Generate report 2", nullptr));
        actionReport_Option->setText(QCoreApplication::translate("MainWindow", "Report Option", nullptr));
        comboBox_pumpmodel_qty->setItemText(0, QCoreApplication::translate("MainWindow", "1", nullptr));
        comboBox_pumpmodel_qty->setItemText(1, QCoreApplication::translate("MainWindow", "2", nullptr));
        comboBox_pumpmodel_qty->setItemText(2, QCoreApplication::translate("MainWindow", "3", nullptr));
        comboBox_pumpmodel_qty->setItemText(3, QCoreApplication::translate("MainWindow", "4", nullptr));

        label_1->setText(QCoreApplication::translate("MainWindow", "\346\263\265\345\236\213\345\217\267\346\225\260", nullptr));
        comboBox_model_number->setItemText(0, QCoreApplication::translate("MainWindow", "1", nullptr));

        label_2->setText(QCoreApplication::translate("MainWindow", "\345\275\223\345\211\215\345\236\213\345\217\267", nullptr));
        groupBox_1->setTitle(QCoreApplication::translate("MainWindow", "\346\260\264\346\263\265\345\222\214\347\224\265\346\234\272\346\250\241\345\236\213", nullptr));
        pushButton_import_pump_curve->setText(QCoreApplication::translate("MainWindow", "\345\257\274\345\205\245\346\260\264\346\263\265\345\222\214\347\224\265\346\234\272\346\250\241\345\236\213", nullptr));
        comboBox_choose_pump_curve->setItemText(0, QCoreApplication::translate("MainWindow", "Flow - Head", nullptr));
        comboBox_choose_pump_curve->setItemText(1, QCoreApplication::translate("MainWindow", "Flow - Power", nullptr));
        comboBox_choose_pump_curve->setItemText(2, QCoreApplication::translate("MainWindow", "Flow - Efficiency", nullptr));
        comboBox_choose_pump_curve->setItemText(3, QCoreApplication::translate("MainWindow", "Flow - NPSHR", nullptr));
        comboBox_choose_pump_curve->setItemText(4, QCoreApplication::translate("MainWindow", "Power - Efficiency", nullptr));

        label_3->setText(QCoreApplication::translate("MainWindow", "\351\200\211\346\213\251\350\246\201\346\211\223\345\215\260\346\233\262\347\272\277", nullptr));
        pushButton_plot_pump_curve->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\215\260\346\260\264\346\263\265\345\222\214\347\224\265\346\234\272\347\213\254\347\253\213\346\233\262\347\272\277", nullptr));
        pushButton_plot_assembly_curve->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\215\260\346\260\264\346\263\265\345\222\214\347\224\265\346\234\272\345\220\210\346\210\220\346\233\262\347\272\277", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("MainWindow", "\347\256\241\350\267\257\347\263\273\347\273\237\346\250\241\345\236\213 ", nullptr));
        pushButton_import_piping_curve->setText(QCoreApplication::translate("MainWindow", "\345\257\274\345\205\245\346\211\254\347\250\213\346\233\262\347\272\277", nullptr));
        pushButton_plot_piping_curve->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\215\260\347\256\241\350\267\257\347\263\273\347\273\237\346\233\262\347\272\277", nullptr));
        comboBox_pump_qty->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_pump_qty->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));
        comboBox_pump_qty->setItemText(2, QCoreApplication::translate("MainWindow", "2", nullptr));
        comboBox_pump_qty->setItemText(3, QCoreApplication::translate("MainWindow", "3", nullptr));
        comboBox_pump_qty->setItemText(4, QCoreApplication::translate("MainWindow", "4", nullptr));
        comboBox_pump_qty->setItemText(5, QCoreApplication::translate("MainWindow", "5", nullptr));
        comboBox_pump_qty->setItemText(6, QCoreApplication::translate("MainWindow", "6", nullptr));
        comboBox_pump_qty->setItemText(7, QCoreApplication::translate("MainWindow", "7", nullptr));
        comboBox_pump_qty->setItemText(8, QCoreApplication::translate("MainWindow", "8", nullptr));

        label_11->setText(QCoreApplication::translate("MainWindow", "\345\275\223\345\211\215\345\236\213\345\217\267\345\256\211\350\243\205\346\225\260\351\207\217", nullptr));
        pushButton_show_import_result->setText(QCoreApplication::translate("MainWindow", "\346\230\276\347\244\272\345\273\272\346\250\241\347\273\223\346\236\234", nullptr));
        plainTextEdit_import_result->setPlainText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("MainWindow", "\346\260\264\346\263\265\345\217\212\347\256\241\350\267\257\345\273\272\346\250\241", nullptr));
        pushButton_plot_sensorless_curve->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\215\260\346\227\240\344\274\240\346\204\237\345\231\250\346\233\262\347\272\277", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "\345\275\223\345\211\215\345\236\213\345\217\267", nullptr));
        comboBox_choose_sensorless_curve->setItemText(0, QCoreApplication::translate("MainWindow", "Power - Flow", nullptr));
        comboBox_choose_sensorless_curve->setItemText(1, QCoreApplication::translate("MainWindow", "Power - Head", nullptr));

        comboBox_model_number_2->setItemText(0, QCoreApplication::translate("MainWindow", "1", nullptr));

        label_5->setText(QCoreApplication::translate("MainWindow", "\351\200\211\346\213\251\350\246\201\346\211\223\345\215\260\346\233\262\347\272\277", nullptr));
        lineEdit_Hz->setInputMask(QString());
        lineEdit_Hz->setText(QCoreApplication::translate("MainWindow", "50", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "\351\242\221\347\216\207 (Hz)", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("MainWindow", "\346\227\240\344\274\240\346\204\237\345\231\250", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "\345\275\223\345\211\215\345\236\213\345\217\267", nullptr));
        comboBox_model_number_3->setItemText(0, QCoreApplication::translate("MainWindow", "1", nullptr));

        pushButton_plot_vfd_curve->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\215\260\350\257\245\351\242\221\347\216\207\344\270\213\347\232\204\346\200\247\350\203\275\346\233\262\347\272\277", nullptr));
        lineEdit_flow->setInputMask(QString());
        lineEdit_flow->setText(QString());
        label_8->setText(QCoreApplication::translate("MainWindow", "\347\233\256\346\240\207\346\265\201\351\207\217 (m3/h)", nullptr));
        lineEdit_head->setInputMask(QString());
        lineEdit_head->setText(QString());
        label_9->setText(QCoreApplication::translate("MainWindow", "\347\233\256\346\240\207\346\211\254\347\250\213(m)", nullptr));
        lineEdit_Hz_calculated->setInputMask(QString());
        lineEdit_Hz_calculated->setText(QString());
        label_10->setText(QCoreApplication::translate("MainWindow", "\351\242\221\347\216\207 (Hz)", nullptr));
        pushButton_Hz_calculation->setText(QCoreApplication::translate("MainWindow", "\350\256\241\347\256\227\347\233\256\346\240\207\351\242\221\347\216\207", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QCoreApplication::translate("MainWindow", "\351\242\221\347\216\207\350\256\241\347\256\227", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "\347\233\256\346\240\207\346\265\201\351\207\217 (m3/h)", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "\347\233\256\346\240\207\346\211\254\347\250\213(m)", nullptr));
        lineEdit_target_head->setInputMask(QString());
        lineEdit_target_head->setText(QString());
        lineEdit_target_flow->setInputMask(QString());
        lineEdit_target_flow->setText(QString());
        pushButton_energy_saving_calculation->setText(QCoreApplication::translate("MainWindow", "\350\256\241\347\256\227\350\212\202\350\203\275\346\226\271\346\241\210", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QCoreApplication::translate("MainWindow", "\350\212\202\350\203\275\350\256\241\347\256\227", nullptr));
        label_p1->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        label_p2->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        label_p3->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        label_p4->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        label_p5->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        label_p6->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        Edit_drive_type_p1->setText(QCoreApplication::translate("MainWindow", "DOL", nullptr));
        Edit_drive_type_p2->setText(QCoreApplication::translate("MainWindow", "DOL", nullptr));
        Edit_drive_type_p3->setText(QCoreApplication::translate("MainWindow", "DOL", nullptr));
        Edit_drive_type_p4->setText(QCoreApplication::translate("MainWindow", "DOL", nullptr));
        Edit_drive_type_p5->setText(QCoreApplication::translate("MainWindow", "DOL", nullptr));
        Edit_drive_type_p6->setText(QCoreApplication::translate("MainWindow", "DOL", nullptr));
        Edit_Hz_p1->setText(QCoreApplication::translate("MainWindow", "50.0", nullptr));
        Edit_Hz_p2->setText(QCoreApplication::translate("MainWindow", "50.0", nullptr));
        Edit_Hz_p3->setText(QCoreApplication::translate("MainWindow", "50.0", nullptr));
        Edit_Hz_p4->setText(QCoreApplication::translate("MainWindow", "50.0", nullptr));
        Edit_Hz_p5->setText(QCoreApplication::translate("MainWindow", "50.0", nullptr));
        Edit_Hz_p6->setText(QCoreApplication::translate("MainWindow", "50.0", nullptr));
        Edit_power_p1->setText(QCoreApplication::translate("MainWindow", "500", nullptr));
        Edit_power_p2->setText(QCoreApplication::translate("MainWindow", "500", nullptr));
        Edit_power_p3->setText(QCoreApplication::translate("MainWindow", "500", nullptr));
        Edit_power_p4->setText(QCoreApplication::translate("MainWindow", "500", nullptr));
        Edit_power_p5->setText(QCoreApplication::translate("MainWindow", "500", nullptr));
        Edit_power_p6->setText(QCoreApplication::translate("MainWindow", "500", nullptr));
        Edit_flow_p1->setText(QCoreApplication::translate("MainWindow", "3000", nullptr));
        Edit_flow_p2->setText(QCoreApplication::translate("MainWindow", "3000", nullptr));
        Edit_flow_p3->setText(QCoreApplication::translate("MainWindow", "3000", nullptr));
        Edit_flow_p4->setText(QCoreApplication::translate("MainWindow", "3000", nullptr));
        Edit_flow_p5->setText(QCoreApplication::translate("MainWindow", "3000", nullptr));
        Edit_flow_p6->setText(QCoreApplication::translate("MainWindow", "3000", nullptr));
        label_uint_Hz->setText(QCoreApplication::translate("MainWindow", "Hz", nullptr));
        label_uint_kW->setText(QCoreApplication::translate("MainWindow", "kW", nullptr));
        label_uint_kW_2->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>m<span style=\" vertical-align:super;\">3</span>/h</p></body></html>", nullptr));
        lineEdit_flow_start->setInputMask(QString());
        lineEdit_flow_start->setText(QCoreApplication::translate("MainWindow", "2000", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>Start flow</p></body></html>", nullptr));
        lineEdit_flow_stop->setInputMask(QString());
        lineEdit_flow_stop->setText(QCoreApplication::translate("MainWindow", "3000", nullptr));
        pushButton_demo_start->setText(QCoreApplication::translate("MainWindow", "START", nullptr));
        Edit_flow_total->setText(QCoreApplication::translate("MainWindow", "12000", nullptr));
        Edit_head->setText(QCoreApplication::translate("MainWindow", "12000", nullptr));
        Edit_efficiency->setText(QCoreApplication::translate("MainWindow", "12000", nullptr));
        label_img_p3->setText(QString());
        label_img_p4->setText(QString());
        label_img_p6->setText(QString());
        label_img_p5->setText(QString());
        label_img_p2->setText(QString());
        label_img_p1->setText(QString());
        label_28->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>Stop flow</p></body></html>", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>Total flow</p></body></html>", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>Head</p></body></html>", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>Efficiency</p></body></html>", nullptr));
        label_uint_kW_3->setText(QCoreApplication::translate("MainWindow", "kW", nullptr));
        label_uint_kW_4->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>m<span style=\" vertical-align:super;\">3</span>/h</p></body></html>", nullptr));
        label_uint_Hz_2->setText(QCoreApplication::translate("MainWindow", "%", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>Total power</p></body></html>", nullptr));
        Edit_power_total->setText(QCoreApplication::translate("MainWindow", "12000", nullptr));
        label_uint_kW_5->setText(QCoreApplication::translate("MainWindow", "m", nullptr));
        label_uint_kW_6->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>m<span style=\" vertical-align:super;\">3</span>/h</p></body></html>", nullptr));
        label_uint_kW_7->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>m<span style=\" vertical-align:super;\">3</span>/h</p></body></html>", nullptr));
        pushButton_demo_clear->setText(QCoreApplication::translate("MainWindow", "CLEAR", nullptr));
        pushButton_test->setText(QCoreApplication::translate("MainWindow", "test", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QCoreApplication::translate("MainWindow", "\346\274\224\347\244\272\345\212\250\347\224\273", nullptr));
        menuSet_DB->setTitle(QCoreApplication::translate("MainWindow", "Settings", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
